In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
data = [[5,2,4,2,1],[9,3,4,3,0],[10,4,3,4,0],[14,1,3,5,0],[12,1,4,3,0],[11,4,2,1,0],[16,5,2,4,0],[7,1,4,2,1]]
df = pd.DataFrame(data,columns=['age','social activity','po','ph','target'])

In [9]:
df

age  social activity  po  ph  target
0    5                2   4   2       1
1    9                3   4   3       0
2   10                4   3   4       0
3   14                1   3   5       0
4   12                1   4   3       0
5   11                4   2   1       0
6   16                5   2   4       0
7    7                1   4   2       1

In [10]:
df.head()

age  social activity  po  ph  target
0    5                2   4   2       1
1    9                3   4   3       0
2   10                4   3   4       0
3   14                1   3   5       0
4   12                1   4   3       0

In [15]:
feature_names = ['age','social activity','po','ph']
target_names = ['target']

In [16]:
X = df[feature_names]
y = df[target_names]

In [17]:
X.head()

age  social activity  po  ph
0    5                2   4   2
1    9                3   4   3
2   10                4   3   4
3   14                1   3   5
4   12                1   4   3

In [18]:
y.head()

target
0       1
1       0
2       0
3       0
4       0

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=123)

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
regr = LogisticRegression()

In [47]:
regr.fit(X_train,y_train)

C:\Users\taishwarya\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
from sklearn.metrics import mean_squared_error

In [49]:
y_pred_test = regr.predict(X_test)
y_pred_test


array([1, 0], dtype=int64)

In [50]:
from collections import OrderedDict

In [57]:
new_data = OrderedDict([('age',12),('social activity',2),('ph',4),('po',1)])

In [58]:
new_data = pd.Series(new_data).values.reshape(1,-1)
regr.predict(new_data)

array([0], dtype=int64)

In [59]:
from sklearn import svm

In [60]:
clf = svm.SVC(kernel = "linear")

In [61]:
clf.fit(X_train,y_train)

C:\Users\taishwarya\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [62]:
y_pred=clf.predict(X_test)

In [63]:
y_pred

array([1, 0], dtype=int64)

In [64]:
from sklearn import metrics 

In [66]:
metrics.accuracy_score(y_test,y_pred)

1.0

In [67]:
metrics.precision_score(y_test,y_pred)

1.0

In [68]:
metrics.recall_score(y_test,y_pred)

1.0

NameError: name 'get_int' is not defined

NameError: name 'get_int' is not defined

Value of IntVar() 100
Value of StringVar() GFG
Value of BooleanVar() False
Value of DoubleVar() 1.236


age
social activity
po
ph
r 2


Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\taishwarya\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-87-395c6bec9105>", line 39, in <lambda>
    command=(lambda e=ents: monthly_payment(e)))
  File "<ipython-input-87-395c6bec9105>", line 10, in monthly_payment
    loan = float(entries['Loan Principle'].get())
KeyError: 'Loan Principle'
